server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first01?serverTimezone=GMT%2B8
    username: root
    password: riit
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.offcn.dao.pojo